export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';
export const AUTO_LOGIN_SUCCESS = 'AUTO_LOGIN_SUCCESS';
export const AUTO_LOGIN_FAILED = 'AUTO_LOGIN_FAILED';
export const LOGOUT = "LOGOUT";

export const REQUEST_USER = 'REQUEST_USER';
export const USER_SAVE = 'USER_SAVE';
export const USER_IS_WORKING = 'USER_IS_WORKING';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_SAVE_SUCCESS = "USER_SAVE_SUCCESS";
export const USER_ERRORED = 'USER_ERRORED';
export const CLEAR_STATUS = 'CLEAR_STATUS';

export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
